routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// routes for user model
Route::resource('users','UserController')->middleware('admin');

// routes for product model
Route::resource('products','ProductController')->middleware('admin');
Route::post('products/publish/{id}','ProductController@publish')->middleware('admin')->name('products.publish');
Route::post('products/{id}/add_variant','ProductController@add_variant')->middleware('admin')->name('products.add_variant');
Route::post('products/{id}/edit_variant','ProductController@edit_variant')->middleware('admin')->name('products.edit_variant');
Route::delete('products/{id}/delete_variant','ProductController@delete_variant')->middleware('admin')->name('products.delete_variant');

// routes for category model
Route::resource('categories','CategoryController')->middleware('admin');

// routes for area model
Route::post('areas/store','AreaController@store')->middleware('admin')->name('areas.store');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //

    protected $fillable =['name','img_url'];

    public function products(){
        return $this->hasMany('App\Product');
    }

    public function area(){
        return $this->belongsTo('App\Area');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use App\Category;
use App\User;
use App\Area;
use Auth;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $areas = Area::all();
        $categories = Category::all();
        return view('categories.index',compact('categories','areas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $areas = Area::all();
        return view('categories.create',compact('areas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category();
        if($request->hasfile('img_url'))
        {
            if($request->file('img_url')->isValid()){
                $img_path = $request->file('img_url')->store('category_img');
            } else {
                return redirect('categories/create')->with('fail','图片上传失败');
            }

        }
        $category->area_id = $request->get('area_id');
        $category->name = $request->get('name');
        if(isset($img_path)){
            $category->img_url = $img_path;
        }
        $category->save();

        return redirect('categories')->with('success','已添加类别');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);
        $products = $category->products;
        return view('categories.show',compact('category','products','id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('categories.edit',compact('category','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        if($request->hasfile('img_url'))
        {
            if($request->file('img_url')->isValid()){
                $img_path = $request->file('img_url')->store('category_img');
            } else {
                return redirect('categories/'.$id.'/edit')->with('fail','图片上传失败');
            }

        }
        $category->name = $request->get('name');
        if(isset($img_path)){
            $category->img_url = $img_path;
        }
        $category->save();
        return redirect('categories')->with('success','更新类别成功');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/categories/category_tab.blade.php
<div class="container-fluid">
    <div class="col-md-4 offset-4 btn-group d-flex" role="group">
        <a href="{{ route('categories.index') }}" class="btn btn-info w-100">全部类别</a>
        <a href="{{ route('categories.create') }}" class="btn btn-info w-100">添加类别</a>
    </div>
</div>

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            @include('categories.category_tab')
            <hr>

            <div class="container-fluid">
                <ul class="nav nav-tabs justify-content-center border-0" role="tablist">
                    <li class="nav-item">
                        <a class="btn btn-info" id="area-tab" data-toggle="tab" href="#area" role="tab"
                           aria-controls="collection" aria-selected="false">
                            房间类别
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-info" id="category-tab" data-toggle="tab" href="#category" role="tab"
                           aria-controls="category" aria-selected="false">
                            产品分类
                        </a>
                    </li>
                </ul>
            </div>

            <div id="area" class="collapse col-md-8">
                <div class="card">
                    <div class="card-header">添加房间类别</div>
                    <div class="card-body">
                        <form method="post" action="{{ route('areas.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('layouts.feedback')
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           name="name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        添加
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            <div id="category" class="collapse col-md-8">
                <div class="card">
                    <div class="card-header">添加产品类别</div>
                    <div class="card-body">
                        <form method="post" action="{{ route('categories.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('layouts.feedback')
                            <div class="form-group row">
                                <label for="img_url" class="col-md-4 col-form-label text-md-right">类别图片</label>

                                <div class="col-md-6">
                                    <input id="img_url" type="file"
                                           class="form-control{{ $errors->has('img_url') ? ' is-invalid' : '' }}"
                                           name="img_url" required autofocus>

                                    @if ($errors->has('img_url'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('img_url') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           name="name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="area_id" class="col-md-4 col-form-label text-md-right">房间类别</label>

                                <div class="col-md-6">
                                    <select name="area_id" class="form-control">
                                        @foreach($areas as $area)
                                            <option value="{{$area->id}}">{{$area->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        添加
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('categories.category_tab')
            <hr>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">编辑类别</div>
                    <div class="card-body">
                        <form method="post" action="{{ action('CategoryController@update',$id) }}"
                              enctype="multipart/form-data">
                            @csrf
                            @include('layouts.feedback')
                            <input name="_method" type="hidden" value="PATCH">
                            <div class="form-group row">
                                <label for="img_url" class="col-md-4 col-form-label text-md-right">更新图片</label>

                                <div class="col-md-6">
                                    <input id="img_url" type="file"
                                           class="form-control{{ $errors->has('img_url') ? ' is-invalid' : '' }}"
                                           name="img_url" autofocus>

                                    @if ($errors->has('img_url'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('img_url') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           name="name" value="{{ $category->name }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        更新
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
            <div class="row justify-content-center">
                @include('categories.category_tab')
            </div>

        <hr>
        @include('layouts.feedback')
        <table class="table table-bordered table-hover text-center">
            <thead>
            <tr>
                <td>
                    <h1>房间类别名称</h1>
                </td>
                <td>
                    <h1>/</h1>
                </td>
                <td>
                    <h1>/</h1>
                </td>
                <td>
                    <h1>操作</h1>
                </td>
            </tr>
            </thead>
            @foreach($areas as $area)
                <tr>
                    <td><h2>{{$area->name}}</h2></td>
                    <td></td>
                    <td></td>
                    <td>
                        <div class="btn-group-vertical d-flex">
                            <button class="btn btn-info">编辑</button>
                            <button class="btn btn-info">显示</button>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td><h2>类别名称</h2></td>
                    <td><h2>图片</h2></td>
                    <td><h2>操作</h2></td>
                </tr>
                @foreach($area->categories as $category)
                    <tr>
                        <td></td>
                        <td><h3>{{$category['name']}}</h3></td>
                        <td class="d-flex justify-content-center"><a href="/furniture/storage/app/{{$category['img_url']}}"  target="_blank"><img src="/furniture/storage/app/{{$category['img_url']}}"
                                                                          style="width:100px;height:100px"> </a> </td>
                        <td>
                            <div class="btn-group-vertical d-flex">
                                <a href="{{action('CategoryController@show', $category['id'])}}" class="btn btn-info">显示</a>
                                <a href="{{action('CategoryController@edit', $category['id'])}}" class="btn btn-info">编辑</a>
                            </div>
                        </td>
                    </tr>

                @endforeach
            @endforeach



        </table>
    </div>

@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('categories.category_tab')
        </div>
        <hr>
        @include('layouts.feedback')
        <table class="table table-bordered table-hover text-center">
            <thead>
            <h1>{{$category->name}}</h1>
            <tr>
                <td>
                    <h1>名称</h1>
                </td>
                <td>
                    <h1>图片</h1>
                </td>
                <td>
                    <h1>价格</h1>
                </td>
                <td>
                    <h1>销量</h1>
                </td>
                <td>
                    <h1>类别</h1>
                </td>
                <td>
                    <h1>操作</h1>
                </td>
            </tr>
            </thead>
            @foreach($products as $product)
                <tr>
                    <td><h1>{{$product['name']}}</h1></td>
                    <td class="d-flex justify-content-center"><img src="../storage/app/{{$product['img_url']}}"
                                                                   style="width:100px;height:100px"></td>
                    <td><h1>{{$product['price']}}</h1></td>
                    <td><h1>{{$product['sale']}}</h1></td>
                    <td><h1>{{$product->category->name}}</h1></td>
                    <td>
                        <div class="btn-group-vertical d-flex">
                            <a href="{{action('ProductController@edit', $product['id'])}}" class="btn btn-info">编辑</a>
                        </div>
                    </td>
                </tr>

            @endforeach

        </table>
    </div>

@endsection