routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// routes for user model
Route::resource('users','UserController')->middleware('admin');

// routes for product model
Route::resource('products','ProductController')->middleware('admin');
Route::post('products/publish/{id}','ProductController@publish')->middleware('admin')->name('products.publish');
Route::post('products/{id}/add_variant','ProductController@add_variant')->middleware('admin')->name('products.add_variant');
Route::post('products/{id}/edit_variant','ProductController@edit_variant')->middleware('admin')->name('products.edit_variant');
Route::delete('products/{id}/delete_variant','ProductController@delete_variant')->middleware('admin')->name('products.delete_variant');

// routes for category model
Route::resource('categories','CategoryController')->middleware('admin');

// routes for area model
Route::post('areas/store','AreaController@store')->middleware('admin')->name('areas.store');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ShoppingCart;

class Product extends Model
{
    protected $fillable =['name','description','img_url','sale','category_id','service','delivery','title','spec','detail_text'];

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function variants(){
        return $this->hasMany('App\Variant');
    }

    public function get_cart_quantity($user_id){
        return ShoppingCart::where('user_id', $user_id)->
            where('product_id',$this->id)->firstOrFail()->quantity;
    }

}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class ProductController extends Controller
{
    /**
     * Fetch all products that are published
     */
    public function index(){
        $products = Product::where('published',true)->get();
        foreach($products as $product){
            try{
                $product['variant'] = $product->variants->first();
            } catch(\Exception $e){
                Log::debug($e);
                return response()->json(['message'=>'error'],200);
            }

        }
        return response()->json(['message'=>'success','data'=>$products],200);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Variant;
use Illuminate\Http\Request;
use App\Product;
use App\Category;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        foreach ($products as $product) {
            $product->img_url = explode("|",$product->img_url)[0];
            $product->published = boolval($product->published);
        }
        return view('products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('products.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        if($files = $request->file('img_url'))
        {
            $images_path = array();
            try{
                foreach($files as $file){
                    if($file->isValid()){
                        $img_path = $file->store('products/images');
                        $images_path[] = $img_path;
                    } else {
                        return redirect(route('products.index'))->with('fail','图片上传失败');
                    }
                }
                $images_path = implode("|",$images_path);
            } catch(\Exception $e){
                foreach($images_path as $img_path){
                    Storage::delete('products/images/'.$img_path);
                }

            }
        } else {
            return redirect(route('products.index'))->with('fail','图片上传失败');
        }
        if($files = $request->file('description'))
        {
            $description_path = array();
            try{
                foreach($files as $file){
                    if($file->isValid()){
                        $img_path = $file->store('products/description');
                        $description_path[] = $img_path;
                    } else {
                        return redirect(route('products.index'))->with('fail','图片上传失败');
                    }
                }
                $description_path = implode("|",$description_path);
            } catch(\Exception $e){
                foreach($description_path as $img_path){
                    Storage::delete('products/description/'.$img_path);
                }

            }
        }

        if(isset($images_path)){
            $data['img_url'] = $images_path;
        }
        if(isset($description_path)){
            $data['description'] = $description_path;
        }
        Product::create($data);
        return redirect('products')->with('success','已添加产品');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        $product->published = boolval($product->published);
        $categories = Category::all();
        return view('products.show',compact('product','categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $product = Product::find($id);
        return view('products.edit',compact('categories','product','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $data = $request->all();
        unset($data['img_url']);
        unset($data['description']);
        if($files = $request->file('img_url'))
        {
            $images_path = array();
            try{
                foreach($files as $file){
                    if($file->isValid()){
                        $img_path = $file->store('products/images');
                        $images_path[] = $img_path;
                    } else {
                        return redirect(route('products.index'))->with('fail','图片上传失败');
                    }
                }
                $images_path = implode("|",$images_path);
            } catch(\Exception $e){
                foreach($images_path as $img_path){
                    Storage::delete('products/images/'.$img_path);
                }
                return redirect(route('products.index'))->with('fail','图片上传失败');
            }
        }
        if($files = $request->file('description'))
        {
            $description_path = array();

            try{
                foreach($files as $file){
                    if($file->isValid()){
                        $img_path = $file->store('products/description');
                        $description_path[] = $img_path;
                    } else {
                        return redirect(route('products.index'))->with('fail','图片上传失败');
                    }
                }
                $description_path = implode("|",$description_path);
            } catch(\Exception $e){
                foreach($description_path as $img_path){
                    Storage::delete('products/description/'.$img_path);
                }

            }
        }
        if(isset($description_path)){
            $data['description']=$description_path;
        }
        if(isset($images_path)){
            $data['img_url']=$images_path;
        }
        $product->update($data);

        return redirect('products')->with('success','已更新产品');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function add_to_cart(){
        
    }

    public function add_variant(Request $request,$id){
        $data = $request->all();
        $data['product_id'] = $id;
        try{
            Variant::create($data);
            return redirect(route('products.show',['id'=>$id]))->with('success','规格创建成功');
        }catch (\Exception $e){
            return redirect(route('products.show',['id'=>$id]))->with('fail','规格创建失败');
        }
    }

    public function edit_variant(Request $request,$id){
        $product = Product::find($id);
        try{
            foreach($product->variants as $variant){
                $data = $request->get("variant_".$variant->id);
                $variant->update($data);
            }
            return redirect(route('products.show',['id'=>$id]))->with('success','规格修改成功');
        } catch (\Exception $e){
            return redirect(route('products.show',['id'=>$id]))->with('fail','规格修改失败，部分数据出错');
        }

    }

    public function delete_variant(Request $request,$id){

    }

    public function publish($id){
        $product = Product::find($id);
        if($product->published){
            $product->published = false;
            $product->save();
            return redirect(route('products.show',['id'=>$product->id]))->with('success','已取消发布');
        } else {
            if($product->variants->isEmpty()){
                return redirect(route('products.show',['id'=>$product->id]))->with('fail','请先添加规格再发布');
            } else {
                $product->published = true;
                $product->save();
                return redirect(route('products.show',['id'=>$product->id]))->with('success','已发布');
            }
        }
    }

}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('products.product_tab')
            <hr>
            <div class="col-md-8">
                @component('products.form',["action"=>"create","categories"=>$categories])
                    @slot('title') 添加产品 @endslot
                    @slot('link'){{route('products.store')}}@endslot
                @endcomponent
            </div>
        </div>
    </div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('products.product_tab')
            <hr>
            <div class="col-md-8">
                @component('products.form',["action"=>"edit","product"=>$product,"categories"=>$categories])
                    @slot('title') 编辑产品 @endslot
                    @slot('link'){{route('products.update',['id'=>$product->id])}}@endslot
                @endcomponent
            </div>
        </div>

    </div>
@endsection

resources/views/products/form.blade.php
<div class="card">
    <div class="card-header">{{$title}}</div>
    <div class="card-body">
        <form method="post" action="{{$link}}" enctype="multipart/form-data">
            @csrf
            @if($action == "edit")
                <input type="hidden" name="_method" value="PATCH">
            @endif
            @include('layouts.feedback')
            <div class="form-group row">
                <label for="img_url" class="col-md-4 col-form-label text-md-right">@if($action=="edit")更新 @endif
                    产品图片</label>

                <div class="col-md-6">
                    <input type="file"
                           class="form-control{{ $errors->has('img_url') ? ' is-invalid' : '' }}"
                           name="img_url[]" @if($action == "create") required @endif multiple autofocus>

                    @if ($errors->has('img_url'))
                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('img_url') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                <div class="col-md-6">
                    <input id="name" type="text"
                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                           name="name"
                           value="@if($action == "create"){{ old('name') }}@else{{$product->name}}@endif" required
                           autofocus>

                    @if ($errors->has('name'))
                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="title" class="col-md-4 col-form-label text-md-right">副名称（选填）</label>

                <div class="col-md-6">
                    <input type="text"
                           class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
                           name="title"
                           value="@if($action == "create"){{ old('name') }}@else{{$product->title}}@endif"
                           autofocus>

                    @if ($errors->has('title'))
                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="service" class="col-md-4 col-form-label text-md-right">服务</label>

                <div class="col-md-6">
                    <input type="text"
                           class="form-control{{ $errors->has('service') ? ' is-invalid' : '' }}"
                           name="service"
                           value="@if($action == "create"){{ old('service') }}@else{{$product->service}}@endif"
                           required autofocus>

                    @if ($errors->has('service'))
                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('service') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="delivery" class="col-md-4 col-form-label text-md-right">物流</label>

                <div class="col-md-6">
                    <input type="text"
                           class="form-control{{ $errors->has('delivery') ? ' is-invalid' : '' }}"
                           name="delivery"
                           value="@if($action == "create"){{ old('delivery') }}@else{{$product->delivery}}@endif"
                           required autofocus>

                    @if ($errors->has('delivery'))
                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('delivery') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="spec" class="col-md-4 col-form-label text-md-right">规格</label>

                <div class="col-md-6">
                    <input type="text"
                           class="form-control{{ $errors->has('spec') ? ' is-invalid' : '' }}"
                           name="spec"
                           value="@if($action == "create"){{ old('spec') }}@else{{$product->spec}}@endif" required
                           autofocus>

                    @if ($errors->has('spec'))
                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('spec') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="description" class="col-md-4 col-form-label text-md-right">@if($action=="edit") 更新 @endif
                    详情介绍（图片）</label>

                <div class="col-md-6">
                    <input id="description" type="file"
                           class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
                           name="description[]" multiple autofocus>

                    @if ($errors->has('description'))
                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="detail_text" class="col-md-4 col-form-label text-md-right">@if($action=="edit") 更新 @endif
                    详情介绍（文字，选填）</label>

                <div class="col-md-6">
                    <textarea id="detail_text"
                           class="form-control{{ $errors->has('detail_text') ? ' is-invalid' : '' }}"
                              name="detail_text" autofocus>@if($action == 'edit'){{$product->detail_text}}@else{{ old('detail_text') }}@endif</textarea>

                    @if ($errors->has('detail_text'))
                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('detail_text') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="price" class="col-md-4 col-form-label text-md-right">类别</label>

                <div class="col-md-6">
                    <select id="category_id"
                            class="form-control{{ $errors->has('category_id') ? ' is-invalid' : '' }}"
                            name="category_id" required autofocus>
                        <option>请选择类别</option>
                        @foreach($categories as $category)
                            <option value="{{$category->id}}"
                                    @if($action == "edit" && $product->category_id == $category->id) selected @endif >{{$category->area->name}}
                                - {{$category->name}}</option>
                        @endforeach
                    </select>
                    @if ($errors->has('category_id'))
                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary btn-block">
                        @if($action == "create") 添加 @else 更新 @endif
                    </button>
                </div>
            </div>

        </form>
    </div>
</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            @include('products.product_tab')
        </div>
        <hr>
        @include('layouts.feedback')
        @component('layouts.table',[
            'key_array'=>['name','img_url','sale','category_id','published'],
            'key_name'=>['名称','图片','销量','类别','是否发布','操作'],
            'data_array'=>$products,
            'show_link'=>'products.show'
        ])

        @endcomponent
    </div>
@endsection

resources/views/products/product_tab.blade.php
<div class="container-fluid">
    <div class="col-md-4 offset-4 btn-group d-flex" role="group">
        <a href="{{ route('products.index') }}" class="btn btn-info w-100">全部产品</a>
        <a href="{{ route('products.create') }}" class="btn btn-info w-100">添加产品</a>
    </div>
</div>