routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// routes for user model
Route::resource('users','UserController')->middleware('admin');

// routes for product model
Route::resource('products','ProductController')->middleware('admin');
Route::post('products/publish/{id}','ProductController@publish')->middleware('admin')->name('products.publish');
Route::post('products/{id}/add_variant','ProductController@add_variant')->middleware('admin')->name('products.add_variant');
Route::post('products/{id}/edit_variant','ProductController@edit_variant')->middleware('admin')->name('products.edit_variant');
Route::delete('products/{id}/delete_variant','ProductController@delete_variant')->middleware('admin')->name('products.delete_variant');

// routes for category model
Route::resource('categories','CategoryController')->middleware('admin');

// routes for area model
Route::post('areas/store','AreaController@store')->middleware('admin')->name('areas.store');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                        <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                    @else
                        @if (auth()->user()->isAdmin())
                            <li><a class="nav-link" href="{{ route('categories.index') }}">{{ __('类别') }}</a></li>
                            <li><a class="nav-link" href="{{ route('products.index') }}">{{ __('产品') }}</a></li>
                            <li><a class="nav-link" href="{{ route('users.index') }}">{{ __('用户') }}</a></li>
                        @endif
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>

                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/layouts/feedback.blade.php
@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif
@if (session('fail'))
    <div class="alert alert-danger">
        {{ session('fail') }}
    </div>
@endif

resources/views/layouts/image_gallery.blade.php
<div id="{{$gallery_id}}" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        @foreach(range(0,count($data_array)-1) as $index)
            <li data-target="#{{$gallery_id}}" data-slide-to="{{$index}}"
                @if($index == 0) class="active" @endif></li>
        @endforeach
    </ol>
    <div class="carousel-inner">
        @foreach($data_array as $data)
            <div class="carousel-item @if($loop->index == 0) active @endif">
                <img class="d-block mx-auto" src="{{asset('storage/app/'.$data)}}" alt="{{$loop->index}} slide" style="width:{{$width}}">
            </div>
        @endforeach
    </div>
    <a class="carousel-control-prev" href="#{{$gallery_id}}" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon bg-info" aria-hidden="true" style="height:50px;width:50px"></span>
        <span class="sr-only">上一张</span>
    </a>
    <a class="carousel-control-next" href="#{{$gallery_id}}" role="button" data-slide="next">
        <span class="carousel-control-next-icon bg-info" aria-hidden="true" style="height:50px;width:50px"></span>
        <span class="sr-only">下一张</span>
    </a>
</div>

resources/views/layouts/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="{{$modal_id}}" tabindex="-1" role="dialog" aria-labelledby="{{$modal_id}}Title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered {{$size}}" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLongTitle">{{$title}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{$content}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/table.blade.php
<table class="table table-bordered table-hover text-center">
    @if(isset($check))
        <button type="submit" class="btn btn-info btn-block">
            更新
        </button>
    @endif
    <thead>
    @foreach($key_name as $key)
        <th>
            {{$key}}
        </th>
    @endforeach
    </thead>
    <tbody>
    @foreach($data_array as $data)
        <tr>
            @foreach($key_array as $key)
                <td> @if(strpos($key,'img') !== false) <a href="{{asset('storage/app/'.$data[$key])}}"
                                                          target="_blank"><img
                                src="{{asset('storage/app/'.$data[$key])}}"
                                style="height:100px;width:100px"></a>
                    @elseif(strpos($key,'category') !== false)
                        {{$data->category->name}}
                    @elseif(strpos($key,'brand'))
                        {{$data->brand->name}}
                    @elseif(is_bool($data[$key]))
                        @if($data[$key])
                            是
                        @else
                            否
                        @endif
                    @else
                        {{$data[$key]}}
                    @endif
                </td>
            @endforeach
            <td>
                <div class="btn-group-vertical">
                    @if(isset($show_link))
                        <a href="{{route($show_link,['id' => $data['id']])}}" class="btn btn-info text-light">显示</a>
                    @endif
                    @if(isset($edit_link))
                        <a href="{{route($edit_link,['id' => $data['id']])}}" class="btn btn-info text-light">编辑</a>
                    @endif
                    @if(isset($check))
                        <input type="checkbox" name="check_list[]"
                               @if($check_type == 'collection')
                               @if($collection->products->contains($data))
                               checked
                               @endif
                               @endif
                               value="{{$data['id']}}">
                    @endif
                </div>
            </td>


        </tr>
    @endforeach
    </tbody>
</table>